# Generated by Django 6.0.4 on 2026-05-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('final_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('final_weight', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DishPreparationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_items', to='foodcost.dish')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcost.preparation')),
            ],
        ),
        migrations.CreateModel(
            name='PreparationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcost.preparation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcost.product')),
            ],
        ),
        migrations.CreateModel(
            name='DishProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='foodcost.dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcost.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_from', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='foodcost.product')),
            ],
        ),
    ]
