# Generated by Django 6.0.4 on 2026-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['-date_from', '-id']},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('g', 'г'), ('l', 'л'), ('ml', 'мл'), ('pcs', 'шт')], max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='date_from',
            field=models.DateField(verbose_name='Дата цены'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена закупки'),
        ),
    ]
