# Generated by Django 6.0.4 on 2026-05-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0002_alter_productprice_options_alter_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Зарплата в месяц')),
                ('monthly_hours', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Часов в месяц')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('g', 'г'), ('l', 'л'), ('ml', 'мл'), ('pcs', 'шт')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
