# Generated by Django 6.0.4 on 2026-05-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0003_employee_alter_productprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyUtilityExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц')),
                ('water', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Вода')),
                ('electricity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Электричество')),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Аренда')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='package_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость упаковки'),
        ),
        migrations.AddField(
            model_name='dish',
            name='package_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Упаковка'),
        ),
        migrations.CreateModel(
            name='DishAdditionalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_expenses', to='foodcost.dish')),
            ],
        ),
    ]
