# Generated by Django 6.0.4 on 2026-05-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0004_monthlyutilityexpense_dish_package_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cooking_minutes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Время приготовления, мин'),
        ),
    ]
