# Generated by Django 6.0.4 on 2026-05-02 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0005_dish_cooking_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название упаковки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость упаковки')),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='package_cost',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='package_name',
        ),
        migrations.AddField(
            model_name='dish',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='foodcost.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='monthlyutilityexpense',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Рабочих часов кухни в месяц'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='cooking_minutes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Время приготовления, мин'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooking_minutes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Время приготовления блюда, мин'),
        ),
        migrations.AddField(
            model_name='dish',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='foodcost.packaging', verbose_name='Упаковка'),
        ),
    ]
