# Generated by Django 6.0.4 on 2026-05-02 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0006_packaging_remove_dish_package_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='packaging',
        ),
        migrations.CreateModel(
            name='DishLaborItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Минуты')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_items', to='foodcost.dish')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcost.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DishPackagingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_items', to='foodcost.dish')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcost.packaging')),
            ],
        ),
    ]
