# Generated by Django 6.0.4 on 2026-05-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0009_dish_tech_card_alter_country_name_alter_country_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishTechStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='foodcost.dish')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
