# Generated by Django 6.0.4 on 2026-05-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0011_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='foodcost.preparation')),
                ('sub_preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_preparations', to='foodcost.preparation')),
            ],
        ),
    ]
