# Generated by Django 6.0.4 on 2026-05-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0014_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Главный админ'), ('admin', 'Администратор'), ('viewer', 'Просмотр'), ('kitchen_staff', 'Сотрудник кухни')], default='viewer', max_length=20),
        ),
    ]
