# Generated by Django 6.0.4 on 2026-05-10 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0015_userprofile_allowed_sections_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writeoff_date', models.DateField()),
                ('item_type', models.CharField(choices=[('product', 'Продукт'), ('preparation', 'Заготовка')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('reason', models.CharField(choices=[('expired', 'Просрочка'), ('spoiled', 'Порча'), ('cooking_error', 'Ошибка приготовления'), ('return', 'Возврат'), ('test', 'Тест'), ('regrading', 'Пересорт'), ('staff_meal', 'Еда для персонала'), ('other', 'Другое')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeoffs', to='foodcost.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeoffs', to=settings.AUTH_USER_MODEL)),
                ('preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeoffs', to='foodcost.preparation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeoffs', to='foodcost.product')),
            ],
        ),
    ]
