# Generated by Django 6.0.4 on 2026-05-11 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0016_writeoff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_handovers', to='foodcost.country')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_handovers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftPreparationNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_needs', to='foodcost.shifthandover')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcost.preparation')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftPurchaseNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_needs', to='foodcost.shifthandover')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcost.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftStopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcost.dish')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_items', to='foodcost.shifthandover')),
            ],
        ),
    ]
