# Generated by Django 6.0.4 on 2026-05-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0018_location_shifthandover_location_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='telegram_thread_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
