# Generated by Django 6.0.4 on 2026-05-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0021_paymentmethod_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cached_foodcost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='dish',
            name='cached_ingredient_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dish',
            name='cached_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='dish',
            name='cached_total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
