# Generated by Django 6.0.4 on 2026-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0023_order_is_cancelled_ordercancelreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparation',
            name='cached_cost_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='preparation',
            name='cached_total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
