# Generated by Django 6.0.4 on 2026-05-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0024_preparation_cached_cost_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='net_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordersource',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
