# Generated by Django 6.0.4 on 2026-05-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0025_order_commission_amount_order_net_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_delivery_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
