# Generated by Django 6.0.4 on 2026-05-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0026_order_customer_delivery_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_customer_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
