# Generated by Django 6.0.4 on 2026-05-22 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0027_order_free_customer_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('rent', 'Аренда'), ('utilities', 'Коммуналка'), ('marketing', 'Реклама'), ('other', 'Прочее')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense_date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_expenses', to='foodcost.country')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_expenses', to='foodcost.location')),
            ],
        ),
    ]
