# Generated by Django 6.0.4 on 2026-05-22 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0028_financialexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersource',
            name='default_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_payment_methods', to='foodcost.paymentmethod'),
        ),
    ]
