# Generated by Django 6.0.4 on 2026-05-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0030_employee_hourly_rate_amount_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
