# Generated by Django 6.0.4 on 2026-05-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0031_alter_employee_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='monthly_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
