# Generated by Django 6.0.4 on 2026-05-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0032_alter_employee_monthly_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
