# Generated by Django 6.0.4 on 2026-05-23 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0033_alter_employee_monthly_salary_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayment',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeepenalty',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeepenalty',
            name='penalty_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='foodcost.employeepenaltytype'),
        ),
        migrations.AlterField(
            model_name='employeepenalty',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('done', 'Отработана'), ('cancelled', 'Отменена')], default='planned', max_length=20),
        ),
    ]
