# Generated by Django 6.0.4 on 2026-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0034_alter_employeepayment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_shift_hours',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_kpi_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_rate_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='kpi_percent',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='planned_hours',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=6),
        ),
    ]
