# Generated by Django 6.0.4 on 2026-05-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0036_customeraddress_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='public_categories',
            field=models.ManyToManyField(blank=True, related_name='public_dishes', to='foodcost.dishcategory'),
        ),
        migrations.CreateModel(
            name='DishGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dishes/gallery/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('crop_data', models.JSONField(blank=True, default=dict)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='foodcost.dish')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DishAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('addon_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_as_addon', to='foodcost.dish')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_links', to='foodcost.dish')),
            ],
            options={
                'ordering': ['group_name', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('dish', 'addon_dish'), name='uniq_dish_addon_dish_addon_dish')],
            },
        ),
    ]
