# Generated by Django 6.0.4 on 2026-05-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0037_dish_public_categories_dishgalleryimage_dishaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='category_photos/'),
        ),
    ]
