# Generated by Django 6.0.4 on 2026-05-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0038_dish_photo_url_dishcategory_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='site_sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
