# Generated by Django 6.0.4 on 2026-05-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0039_deliveryzone_center_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('desktop_image', models.URLField(blank=True, default='', max_length=1000)),
                ('mobile_image', models.URLField(blank=True, default='', max_length=1000)),
                ('action_type', models.CharField(choices=[('category', 'Категория'), ('product', 'Товар'), ('external_url', 'Внешняя ссылка'), ('none', 'Без действия')], default='none', max_length=20)),
                ('action_value', models.CharField(blank=True, default='', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_banners', to='foodcost.country')),
            ],
            options={
                'verbose_name': 'Баннер на главной',
                'verbose_name_plural': 'Баннеры на главной',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageProductBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Часто заказывают вместе', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_product_blocks', to='foodcost.country')),
            ],
            options={
                'verbose_name': 'Блок на главной',
                'verbose_name_plural': 'Блоки на главной',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageProductBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcost.homepageproductblock')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_block_items', to='foodcost.dish')),
            ],
            options={
                'verbose_name': 'Товар в блоке',
                'verbose_name_plural': 'Товары в блоке',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('block', 'dish'), name='uniq_homepage_block_dish')],
            },
        ),
    ]
