# Generated by Django 6.0.4 on 2026-05-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0040_homepagebanner_homepageproductblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanner',
            name='show_text',
            field=models.BooleanField(default=True),
        ),
    ]
