# Generated by Django 6.0.4 on 2026-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0041_homepagebanner_show_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dishcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=255),
        ),
    ]
