# Generated by Django 6.0.4 on 2026-05-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0042_alter_dish_slug_alter_dishcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCompactUpsellBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Часто заказывают вместе', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_compact_upsell_blocks', to='foodcost.country')),
            ],
            options={
                'verbose_name': 'Компактный блок допродаж',
                'verbose_name_plural': 'Компактные блоки допродаж',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageCompactUpsellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcost.homepagecompactupsellblock')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_compact_upsell_items', to='foodcost.dish')),
            ],
            options={
                'verbose_name': 'Товар в компактном блоке',
                'verbose_name_plural': 'Товары в компактном блоке',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('block', 'dish'), name='uniq_compact_upsell_block_dish')],
            },
        ),
    ]
