# Generated by Django 6.0.4 on 2026-05-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0043_homepagecompactupsellblock_homepagecompactupsellitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('awaiting_payment', 'Ожидает оплаты'), ('cooking', 'Готовится'), ('delivery', 'Доставка'), ('done', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=30),
        ),
    ]
