# Generated by Django 6.0.4 on 2026-05-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0044_order_payment_paid_at_order_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('awaiting_payment', 'Ожидает оплаты'), ('payment_failed', 'Оплата не прошла'), ('cooking', 'Готовится'), ('delivery', 'Доставка'), ('done', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=30),
        ),
    ]
