# Generated by Django 6.0.4 on 2026-05-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0045_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount_tiyin', models.BigIntegerField()),
                ('state', models.IntegerField(default=1)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('payme_time_ms', models.BigIntegerField()),
                ('create_time_ms', models.BigIntegerField()),
                ('perform_time_ms', models.BigIntegerField(default=0)),
                ('cancel_time_ms', models.BigIntegerField(default=0)),
                ('raw_last_params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payme_transactions', to='foodcost.order')),
            ],
            options={
                'verbose_name': 'Транзакция Payme',
                'verbose_name_plural': 'Транзакции Payme',
                'ordering': ['-created_at'],
            },
        ),
    ]
