# Generated by Django 6.0.4 on 2026-05-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0046_paymetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_expired',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.DeleteModel(
            name='PaymeTransaction',
        ),
    ]
