# Generated by Django 6.0.4 on 2026-05-29 21:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0048_remove_order_auto_expired_dish_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecompactupsellblock',
            name='placement',
            field=models.CharField(choices=[('home', 'Главная страница'), ('cart', 'Корзина')], db_index=True, default='home', max_length=16),
        ),
        migrations.CreateModel(
            name='HomeComboBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(blank=True, default='', max_length=100)),
                ('cta_label', models.CharField(max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='combo_banners/')),
                ('background_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('background_color', models.CharField(default='#181818', max_length=9, validators=[django.core.validators.RegexValidator(message='background_color must be a HEX color (e.g. #181818).', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('text_color', models.CharField(choices=[('white', 'Белый'), ('dark', 'Тёмный')], default='white', max_length=8)),
                ('cta_action_type', models.CharField(choices=[('category', 'Категория'), ('product', 'Товар'), ('promo_code', 'Промокод (копирование)'), ('external_url', 'Внешняя ссылка'), ('none', 'Без действия')], default='none', max_length=20)),
                ('cta_action_value', models.CharField(blank=True, default='', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_combo_banners', to='foodcost.country')),
            ],
            options={
                'verbose_name': 'Combo-баннер на главной',
                'verbose_name_plural': 'Combo-баннеры на главной',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
