# Generated by Django 6.0.4 on 2026-05-30 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0049_homepagecompactupsellblock_placement_homecombobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_expired',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount_tiyin', models.BigIntegerField()),
                ('state', models.IntegerField(default=1)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('payme_time_ms', models.BigIntegerField()),
                ('create_time_ms', models.BigIntegerField()),
                ('perform_time_ms', models.BigIntegerField(default=0)),
                ('cancel_time_ms', models.BigIntegerField(default=0)),
                ('raw_last_params', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payme_transactions', to='foodcost.order')),
            ],
            options={
                'verbose_name': 'Транзакция Payme',
                'verbose_name_plural': 'Транзакции Payme',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DishUpsellLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('from_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_links', to='foodcost.dish')),
                ('to_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_targeted_by', to='foodcost.dish')),
            ],
            options={
                'verbose_name': 'Привязка допродажи',
                'verbose_name_plural': 'Привязки допродаж',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('from_dish', 'to_dish'), name='uniq_dish_upsell_link_pair'), models.CheckConstraint(condition=models.Q(('from_dish', models.F('to_dish')), _negated=True), name='dish_upsell_link_no_self')],
            },
        ),
    ]
