# Generated by Django 6.0.4 on 2026-05-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0050_order_auto_expired_paymetransaction_dishupselllink'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meta_capi_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='True after the server-side Meta CAPI Purchase event was successfully accepted by Meta. Prevents duplicate sends.'),
        ),
        migrations.AddField(
            model_name='order',
            name='meta_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text="UUID v4 generated by the public site's checkout. Shared with the Meta Pixel client-side event so server-side CAPI Purchase can deduplicate against it.", max_length=64),
        ),
        migrations.AddField(
            model_name='promocode',
            name='usage_limit',
            field=models.CharField(choices=[('none', 'Без ограничений'), ('first_order', 'Только первый заказ')], default='none', help_text='«Без ограничений» — промокод действует сколько угодно раз. «Только первый заказ» — применяется только если у клиента (по номеру телефона) нет ни одного предыдущего успешного или активного заказа.', max_length=20),
        ),
    ]
