# Generated by Django 6.0.4 on 2026-05-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0051_order_meta_capi_sent_order_meta_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_legacy_import',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='legacy_order_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='legacy_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
