# Generated by Django 6.0.4 on 2026-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0052_order_is_legacy_import_order_legacy_order_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delivery_block_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
