# Generated by Django 6.0.4 on 2026-06-01 07:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0053_customer_delivery_block_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeoffs', to='foodcost.location'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('inventory_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'Проводится'), ('awaiting', 'Ожидает проверки'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена')], db_index=True, default='draft', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='foodcost.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories_created', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='foodcost.location')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Продукт'), ('preparation', 'Заготовка')], max_length=20)),
                ('system_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('fact_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcost.inventory')),
                ('preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='foodcost.preparation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='foodcost.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_receipts', to='foodcost.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='foodcost.location')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='foodcost.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcost.purchasereceipt')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.TextField(blank=True, default='')),
                ('telegram', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='foodcost.country')),
            ],
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='foodcost.supplier'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='foodcost.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='foodcost.location')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='foodcost.location')),
            ],
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Продукт'), ('preparation', 'Заготовка')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='foodcost.preparation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='foodcost.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcost.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('purchase_receipt', 'Приход'), ('transfer', 'Перемещение'), ('inventory', 'Инвентаризация')], max_length=30)),
                ('document_id', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=64)),
                ('field', models.CharField(blank=True, default='', max_length=128)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_logs', to='foodcost.country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['document_type', 'document_id', 'created_at'], name='foodcost_do_documen_bf8d79_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Продукт'), ('preparation', 'Заготовка')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('movement_type', models.CharField(choices=[('receipt', 'Приход'), ('sale', 'Списание по заказу'), ('writeoff', 'Списание ручное'), ('transfer_out', 'Перемещение (выход)'), ('transfer_in', 'Перемещение (вход)'), ('inventory_adjustment', 'Инвентаризация'), ('return_cancel', 'Возврат от отмены')], db_index=True, max_length=30)),
                ('source_type', models.CharField(blank=True, choices=[('purchase_receipt', 'Приход'), ('order', 'Заказ'), ('writeoff', 'Списание'), ('transfer', 'Перемещение'), ('inventory', 'Инвентаризация')], default='', max_length=30)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('movement_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='foodcost.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='foodcost.preparation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='foodcost.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='foodcost.location')),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'warehouse', 'product'], name='foodcost_st_country_85e86b_idx'), models.Index(fields=['country', 'warehouse', 'preparation'], name='foodcost_st_country_d8fb24_idx'), models.Index(fields=['source_type', 'source_id'], name='foodcost_st_source__9c3240_idx'), models.Index(fields=['movement_datetime'], name='foodcost_st_movemen_1e372d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='foodcost.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='foodcost.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'product')},
            },
        ),
    ]
