# Generated by Django 6.0.4 on 2026-06-01 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0054_product_minimum_stock_product_sku_writeoff_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pay_type',
            field=models.CharField(choices=[('hourly', 'Почасовая'), ('shift', 'Посменная'), ('salary', 'Оклад')], default='hourly', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='break_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Дневная'), ('night', 'Ночная')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('done', 'Отработана'), ('cancelled', 'Отменена'), ('missed', 'Пропуск'), ('late', 'Опоздание')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeePayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('salary', 'Начисление зарплаты'), ('payout', 'Выплата'), ('advance', 'Аванс'), ('penalty', 'Штраф'), ('bonus', 'Премия'), ('correction', 'Корректировка')], max_length=20)),
                ('entry_date', models.DateField()),
                ('period', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('done', 'Проведено'), ('planned', 'Планируется')], default='done', max_length=12)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='foodcost.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_entries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='foodcost.employee')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
