# Generated by Django 6.0.4 on 2026-06-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0055_employee_hire_date_employee_pay_type_employee_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshift',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('in_progress', 'Идёт'), ('done', 'Отработана'), ('cancelled', 'Отменена'), ('missed', 'Пропуск'), ('late', 'Опоздание')], default='planned', max_length=20),
        ),
    ]
