# Generated by Django 6.0.4 on 2026-06-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0056_alter_employeeshift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('cook', 'Повар'), ('cashier', 'Кассир'), ('cleaner', 'Клинер')], default='', max_length=20),
        ),
    ]
