# Generated by Django 6.0.4 on 2026-06-01 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0057_employee_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shifthandover',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='from_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_from', to='foodcost.employee'),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('viewed', 'Просмотрена'), ('expired', 'Истекла'), ('archived', 'В архиве')], default='created', max_length=12),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='viewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_handovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShiftHandoverTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_done', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='foodcost.shifthandover')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
