# Generated by Django 6.0.4 on 2026-06-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0052_order_meta_match_fields'),
        ('foodcost', '0058_shifthandover_expires_at_shifthandover_from_employee_and_more'),
    ]

    operations = [
    ]
