# Generated by Django 6.0.4 on 2026-06-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0059_merge_20260602_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meta_refund_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='True after the server-side Meta CAPI Refund event was successfully accepted by Meta (order cancelled after Purchase was reported). Prevents duplicate refund sends.'),
        ),
    ]
