# Generated by Django 6.0.4 on 2026-06-02 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0060_order_meta_refund_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DishComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='foodcost.dish')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_combos', to='foodcost.dish')),
            ],
        ),
    ]
