# Generated by Django 6.0.4 on 2026-06-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0061_dish_is_combo_dishcomboitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fbclid',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, default='', help_text='UTM-кампания — ключ для агрегации выручки и сопоставления с расходами Meta.', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_term',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
