# Generated by Django 6.0.4 on 2026-06-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0062_order_fbclid_order_utm_campaign_order_utm_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='eligible_dishes',
            field=models.ManyToManyField(blank=True, help_text='Блюда, на которые распространяется скидка. Пусто = скидка на весь заказ.', related_name='promo_codes', to='foodcost.dish'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='promocode',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='promocode',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='promocode',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='promocode',
            name='utm_term',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
