# Generated by Django 6.0.4 on 2026-06-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0063_promocode_eligible_dishes_promocode_utm_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Действует с этой даты. Пусто — без нижней границы.', null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Действует по эту дату включительно. Пусто — бессрочно.', null=True),
        ),
    ]
