# Generated by Django 6.0.4 on 2026-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0064_promocode_valid_from_promocode_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cash_max_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Максимальная сумма для оплаты наличными (UZS). Выше — только картой. 0 — без ограничения.', max_digits=12),
        ),
        migrations.AddField(
            model_name='country',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Минимальная сумма заказа (UZS). 0 — без ограничения.', max_digits=12),
        ),
    ]
