# Generated by Django 6.0.4 on 2026-06-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0065_country_cash_max_amount_country_min_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('percent_off', 'Скидка %'), ('amount_off', 'Скидка суммой'), ('buy_x_pay_y', 'N по цене M'), ('gift', 'Подарок')], max_length=20)),
                ('label', models.CharField(help_text='Текст бейджа/акции, который видит покупатель (напр. «2 по цене 1»).', max_length=255)),
                ('style', models.CharField(choices=[('red', 'Красный'), ('purple', 'Фиолетовый'), ('green', 'Зелёный'), ('gray', 'Серый')], default='gray', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('stackable', models.BooleanField(default=False, help_text='Можно ли сочетать с другими акциями.')),
                ('priority', models.IntegerField(default=0, help_text='Чем больше, тем раньше применяется при конфликте.')),
                ('scope_type', models.CharField(choices=[('all', 'Все блюда'), ('include', 'Только выбранные'), ('exclude', 'Все, кроме выбранных')], default='all', max_length=10)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, help_text='Для «Скидка %»: процент (напр. 15).', max_digits=5, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Для «Скидка суммой»: сумма скидки (UZS).', max_digits=12, null=True)),
                ('buy_quantity', models.PositiveIntegerField(blank=True, help_text='Сколько нужно купить (для «3 по цене 2» = 3).', null=True)),
                ('pay_quantity', models.PositiveIntegerField(blank=True, help_text='Сколько оплачивается (для «3 по цене 2» = 2).', null=True)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Подарок при сумме корзины от (UZS). Пусто — не по сумме.', max_digits=12, null=True)),
                ('gift_quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='foodcost.country')),
                ('excludes', models.ManyToManyField(blank=True, help_text='Акции, с которыми эта НЕ сочетается.', to='foodcost.promotion')),
                ('gift_dish', models.ForeignKey(blank=True, help_text='Какое блюдо дарим.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_as_gift', to='foodcost.dish')),
                ('required_dishes', models.ManyToManyField(blank=True, help_text='Подарок при наличии этих блюд в корзине.', related_name='promotions_required', to='foodcost.dish')),
                ('scope_dishes', models.ManyToManyField(blank=True, related_name='promotions_scope', to='foodcost.dish')),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
    ]
