# Generated by Django 6.0.4 on 2026-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0066_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='scope',
            field=models.CharField(choices=[('auto', 'Авто (как раньше)'), ('all', 'На весь заказ'), ('include', 'Только выбранные блюда'), ('exclude', 'Все блюда, кроме выбранных')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
