# Generated by Django 6.0.4 on 2026-06-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0067_promocode_scope_promotion_time_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
