# Generated by Django 6.0.4 on 2026-06-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0068_dish_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_hash', models.CharField(db_index=True, max_length=128)),
                ('refresh_hash', models.CharField(db_index=True, max_length=128)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('platform', models.CharField(blank=True, default='', max_length=20)),
                ('device_name', models.CharField(blank=True, default='', max_length=120)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='foodcost.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='foodcost.country')),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'created_at'], name='foodcost_ot_phone_1013ed_idx')],
            },
        ),
    ]
