# Generated by Django 6.0.4 on 2026-06-07 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0070_alter_order_status_devicetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialexpense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialexpense',
            name='legal_entity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='financialexpense',
            name='purchase_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_expenses', to='foodcost.purchasereceipt'),
        ),
        migrations.AddField(
            model_name='financialexpense',
            name='source',
            field=models.CharField(blank=True, choices=[('cash_register', 'Касса точки'), ('settlement_account', 'Расчётный счёт'), ('company_account', 'Счёт компании'), ('debt', 'Долг')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='financialexpense',
            name='expense_type',
            field=models.CharField(choices=[('rent', 'Аренда Махаля (ЖКХ)'), ('representation', 'Представительские'), ('equipment', 'Оборудование'), ('construction', 'Стройка'), ('inventory_items', 'Инвентарь'), ('purchase', 'Закупка'), ('legal', 'Юридические услуги'), ('salary', 'Персонал (зп)'), ('freight', 'Груз. перевозки'), ('fuel', 'Топливо'), ('hosting', 'Хостинг/домен/телефония'), ('corp_car', 'Затраты на корп авто (ремонт)'), ('kitchen_secondary', 'Вторичка для кухни (химия + пром)'), ('packaging', 'Упаковка'), ('marketing', 'Маркетинг (реклама)'), ('development', 'Разработка и поддержка'), ('merch', 'Мерч'), ('other', 'Прочие'), ('utilities', 'Коммуналка (старое)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='financialexpense',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ExpenseDebtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_debtors', to='foodcost.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='financialexpense',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='foodcost.expensedebtor'),
        ),
    ]
