# Generated by Django 6.0.4 on 2026-06-07 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0071_financialexpense_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='show_in_combo_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='home_block_2_sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='in_home_block_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='in_home_block_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='category_logos/'),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='OrderItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addon_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_order_addon', to='foodcost.dish')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='foodcost.orderitem')),
            ],
        ),
    ]
