# Generated by Django 6.0.4 on 2026-06-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0072_dish_show_in_combo_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='badge_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='badge_style',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='delivery_time_label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
