# Generated by Django 6.0.4 on 2026-06-09 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0073_dishcategory_badge_label_dishcategory_badge_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='mxik_code',
            field=models.CharField(blank=True, default='', help_text='ИКПУ/mxik (фискальный). Пока в Uzum не передаётся.', max_length=32),
        ),
        migrations.AddField(
            model_name='dish',
            name='package_code',
            field=models.CharField(blank=True, default='', help_text='Код упаковки (фискальный).', max_length=32),
        ),
        migrations.AddField(
            model_name='dish',
            name='uzum_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена для Uzum. Пусто → используется selling_price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='uzum_stop',
            field=models.BooleanField(default=False, help_text='Стоп только для Uzum (на сайт/приложение не влияет).'),
        ),
        migrations.AddField(
            model_name='location',
            name='uzum_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='uzum_eats_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='UzumApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Uzum Tezkor', max_length=255)),
                ('client_id', models.CharField(max_length=128, unique=True)),
                ('client_secret', models.CharField(max_length=256)),
                ('access_token', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('token_issued_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzum_apps', to='foodcost.country')),
            ],
        ),
    ]
