# Generated by Django 6.0.4 on 2026-06-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0074_dish_mxik_code_dish_package_code_dish_uzum_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Принят'), ('cooking', 'Готовится'), ('ready', 'Готов'), ('awaiting_payment', 'Ожидает оплаты'), ('payment_failed', 'Оплата не прошла'), ('delivery', 'Доставка'), ('done', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=30),
        ),
    ]
