# Generated by Django 6.0.4 on 2026-06-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0075_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishavailability',
            name='uzum_stop',
            field=models.BooleanField(default=False),
        ),
    ]
