# Generated by Django 6.0.4 on 2026-06-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0076_dishavailability_uzum_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='uzum_excluded',
            field=models.BooleanField(default=False, help_text='Не передавать блюдо в Uzum вообще (для незапущенных позиций).'),
        ),
    ]
