# Generated by Django 6.0.4 on 2026-06-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0077_dish_uzum_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersource',
            name='is_uzum',
            field=models.BooleanField(default=False),
        ),
    ]
