# Generated by Django 6.0.4 on 2026-06-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0078_ordersource_is_uzum'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='yandex_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена для Яндекса. Пусто → используется цена Uzum, иначе selling_price.', max_digits=10, null=True),
        ),
    ]
