# Generated by Django 6.0.4 on 2026-06-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0079_dish_yandex_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparation',
            name='cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparations', to='foodcost.employee'),
        ),
    ]
