# Generated by Django 6.0.4 on 2026-06-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0080_preparation_cook'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(default='Обед дня', max_length=120)),
                ('delivery_from', models.CharField(blank=True, default='', help_text="Напр. '11:00' — показывается как «Доставка с 11:00».", max_length=20)),
                ('combo_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('separate_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('soup_name', models.CharField(blank=True, default='', max_length=255)),
                ('main_name', models.CharField(blank=True, default='', max_length=255)),
                ('salad_name', models.CharField(blank=True, default='', max_length=255)),
                ('drink_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_menus', to='foodcost.country')),
                ('drink_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foodcost.dish')),
                ('main_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foodcost.dish')),
                ('salad_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foodcost.dish')),
                ('soup_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foodcost.dish')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('country', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LunchCorporateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.PositiveIntegerField()),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_corporate_tiers', to='foodcost.country')),
            ],
            options={
                'ordering': ['min_qty'],
                'unique_together': {('country', 'min_qty')},
            },
        ),
        migrations.CreateModel(
            name='LunchUpsell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='foodcost.dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsells', to='foodcost.lunchmenu')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('menu', 'dish')},
            },
        ),
    ]
