# Generated by Django 6.0.4 on 2026-06-12 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0081_lunchmenu_lunchcorporatetier_lunchupsell'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLunchCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(default='Обед дня', max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('composition', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lunch_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foodcost.lunchmenu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_combos', to='foodcost.order')),
            ],
        ),
    ]
