# Generated by Django 6.0.4 on 2026-06-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0082_orderlunchcombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lunch_combo_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='lunch_corporate_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
