# Generated by Django 6.0.4 on 2026-06-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0083_order_lunch_combo_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchmenu',
            name='bread_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foodcost.dish'),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='bread_grams',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='bread_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='drink_grams',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='main_grams',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='salad_grams',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='soup_grams',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
