# Generated by Django 6.0.4 on 2026-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0084_lunchmenu_bread_dish_lunchmenu_bread_grams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchmenu',
            name='bread_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='drink_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='main_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='salad_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lunchmenu',
            name='soup_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
