# Generated by Django 6.0.4 on 2026-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0085_lunchmenu_bread_price_lunchmenu_drink_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='uzum_name',
            field=models.CharField(blank=True, default='', help_text='Название блюда для выгрузки в Uzum. Пусто → обычное название блюда.', max_length=255),
        ),
    ]
