# Generated by Django 6.0.4 on 2026-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0086_dish_uzum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='zone_kind',
            field=models.CharField(choices=[('regular', 'Обычная'), ('lunch', 'Обеденная (Обед дня)')], default='regular', help_text='Обеденная зона действует только для заказов с обед-комбо.', max_length=10),
        ),
        migrations.AddField(
            model_name='dish',
            name='site_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dish',
            name='uzum_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dish',
            name='yandex_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
