# Generated by Django 6.0.4 on 2026-06-18 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0087_deliveryzone_zone_kind_dish_site_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('revenue', 'Выручка'), ('investment', 'Инвестиции / взнос'), ('loan', 'Заём / кредит'), ('debt_return', 'Возврат долга нам'), ('other', 'Прочее')], default='', max_length=30)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('income_date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_incomes', to='foodcost.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_incomes', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_incomes', to='foodcost.location')),
            ],
            options={
                'ordering': ['-income_date', '-id'],
            },
        ),
    ]
