# Generated by Django 6.0.4 on 2026-06-28 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0088_financialincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lunches/')),
                ('photo_url', models.URLField(blank=True, default='', max_length=1000)),
                ('badge', models.CharField(blank=True, choices=[('popular', 'Популярный'), ('best_value', 'Выгодный')], default='', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_cutoff', models.CharField(blank=True, default='', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunches', to='foodcost.country')),
            ],
            options={
                'ordering': ['date', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LunchSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Стандарт', max_length=60)),
                ('is_default', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight_total', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='foodcost.lunch')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LunchSizeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('soup', 'Суп'), ('main', 'Горячее'), ('side', 'Гарнир'), ('salad', 'Салат'), ('drink', 'Напиток'), ('bread', 'Хлеб'), ('sauce', 'Соус'), ('dessert', 'Десерт'), ('other', 'Другое')], default='other', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('weight', models.CharField(blank=True, default='', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('net', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('cost_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foodcost.dish')),
                ('preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foodcost.preparation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foodcost.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcost.lunchsize')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
