# Generated by Django 6.0.4 on 2026-06-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0090_lunchsizeitem_extra_max_lunchsizeitem_extra_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlunchcombo',
            name='extras',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
