# Generated by Django 6.0.4 on 2026-06-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0091_orderlunchcombo_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='upsell_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
