# Generated by Django 6.0.4 on 2026-07-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0092_dish_upsell_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_corporate',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
