# Generated by Django 6.0.4 on 2026-09-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcost', '0093_customer_is_corporate'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparation',
            name='tech_card',
            field=models.TextField(blank=True, default='', verbose_name='Техкарта приготовления'),
        ),
    ]
